sudo: false
language: python

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# install required system libraries
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # use miniconda to install numpy/scipy, to avoid lengthy build from source
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # conda-build must be installed in the conda root environment
  - conda install conda-build=2.1.17
  - conda config --add channels python-control
  - conda info -a
  - conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pip coverage
  - source activate test-environment
  # coveralls not in conda repos
  - pip install coveralls

# Install packages
install:
  - conda build --python "$TRAVIS_PYTHON_VERSION" conda-recipe
  - conda install control --use-local

# command to run tests
script:
  # Before installing Slycot
  - python setup.py test

  # Now, get and use Slycot
  - conda install slycot
  - coverage run setup.py test

after_success:
  - coveralls
