language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

# install required system libraries
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update --fix-missing -qq
  - sudo apt-get install gfortran liblapack-dev
  # use miniconda to install numpy/scipy, to avoid lengthy build from source
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION coverage nose numpy scipy matplotlib pip
  - pip install coveralls
  - pip install slycot

# command to run tests
script:
  - coverage run --source=control setup.py test
after_success:
  - coveralls
